/*
MixProcessing - Live Mixing of Processing Sketches 
https://github.com/itschleemilch/MixProcessing

Copyright (c) 2014 Sebastian Schleemilch

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * JS Library for remote accessing MixProcessing's scripting API.
 * 
 * This file was automatic generated by a programm:
 * de.itschleemilch.mixprocessing.util.JS_API_Generator 
 * 
 * Example usage: 
 * Api.environmentListChannels( function(data) {
 *  alert(JSON.stringify(data);
 * } );
 */
var Api = {};

/**
 * Performs an MixProcessing remote API call.
 * 
 * @param String remoteCall
 * @param function callBackFunction is called with 1 json data argument 
 *                                  after receiving the response. Can be null.
 */
Api.apiCall = function (remoteCall, callBackFunction) {
    "use strict";
    var ajax = new XMLHttpRequest();
    ajax.onload = function () {
        var jsonData = JSON.parse(this.responseText);
        if (callBackFunction !== null) {
            callBackFunction(jsonData);
        }
    };
    ajax.open("get", "api/api1/?" + escape(remoteCall), true);
    ajax.send();
};