/*
MixProcessing - Live Mixing of Processing Sketches 
https://github.com/itschleemilch/MixProcessing

Copyright (c) 2014 Sebastian Schleemilch

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package de.itschleemilch.mixprocessing;

import de.itschleemilch.mixprocessing.util.InternetShortcuts;
import de.itschleemilch.mixprocessing.util.SinglePreference;
import java.awt.FileDialog;
import java.io.File;
import java.io.FilenameFilter;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;

/**
 *
 * @author Sebastian Schleemilch
 */
public class ProcessingLibraryLoader extends java.awt.Frame {
    private final FileDialog fileDialog;
    /**
     * Creates new form ProcessingLibLoader
     */
    public ProcessingLibraryLoader() {
        initComponents();
        
        fileDialog = new FileDialog(this, "Open Library");
        fileDialog.setMultipleMode(false);
        fileDialog.setFile("*.jar");
        fileDialog.setFilenameFilter(new FilenameFilter() {
            @Override
            public boolean accept(File dir, String name) {
                return dir.isDirectory() || name.endsWith(".jar");
            }
        });
        
        // Load path settings
        pathField.setText( SinglePreference.getPreference("classpath", "") );
    }
    
    private void addLibraryToClasspath(URL url) {
        URLClassLoader classLoader = (URLClassLoader) ClassLoader.getSystemClassLoader();
        Class<?> clazz = URLClassLoader.class;

        try {
            Method method = clazz.getDeclaredMethod("addURL", new Class<?>[]{URL.class});
            method.setAccessible(true);
            method.invoke(classLoader, new Object[]{url});
        } catch (NoSuchMethodException | SecurityException | 
                IllegalAccessException | IllegalArgumentException | 
                InvocationTargetException e) {
            e.printStackTrace(System.err);
        }
    }
    
    /**
     * Searches for all jar Files and adds them to the Classpath
     * @param dir scanned directory
     */
    private void scanDirectory(File dir) {
        File[] files = dir.listFiles();
        for(File file : files) {
            if(file.isFile() && file.getName().endsWith(".jar")) {
                try {
                    addLibraryToClasspath( file.toURI().toURL() );
                } catch (MalformedURLException e) {
                    e.printStackTrace(System.err);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        label3 = new java.awt.Label();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        pathField = new java.awt.TextField();
        searchBtn = new java.awt.Button();
        startBtn = new java.awt.Button();
        abortBtn = new java.awt.Button();
        downloadLibraryBtn = new java.awt.Button();

        setTitle("Load Library");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setText("MixProcessing Startup");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(label3, gridBagConstraints);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setText("Search for missing Processing 2.x  / 3.x librarys");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(label1, gridBagConstraints);

        label2.setText("Specify the Location of core.jar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(label2, gridBagConstraints);

        pathField.setText("...\\processing-3.0a2\\core\\library");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(pathField, gridBagConstraints);

        searchBtn.setLabel("...");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(searchBtn, gridBagConstraints);

        startBtn.setLabel("Start");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(startBtn, gridBagConstraints);

        abortBtn.setLabel("Abort");
        abortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abortBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(abortBtn, gridBagConstraints);

        downloadLibraryBtn.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        downloadLibraryBtn.setLabel("Download Processing Software");
        downloadLibraryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadLibraryBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(downloadLibraryBtn, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                fileDialog.setVisible(true);
                pathField.setText( fileDialog.getDirectory() );
            }
        }).start();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                scanDirectory( new File(pathField.getText()) );
                // Store path setting
                SinglePreference.setPreference("classpath", pathField.getText());
                // Close frame -> back to main method
                setVisible(false);
            }
        }).start();
    }//GEN-LAST:event_startBtnActionPerformed

    private void abortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abortBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_abortBtnActionPerformed

    private void downloadLibraryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadLibraryBtnActionPerformed
        InternetShortcuts.openShortcut(InternetShortcuts.PROCESSING_DOWNLOAD);
    }//GEN-LAST:event_downloadLibraryBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button abortBtn;
    private java.awt.Button downloadLibraryBtn;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField pathField;
    private java.awt.Button searchBtn;
    private java.awt.Button startBtn;
    // End of variables declaration//GEN-END:variables

    private static final long serialVersionUID = 1L;
}
