/*
 MixProcessing - Live Mixing of Processing Sketches 
 https://github.com/itschleemilch/MixProcessing

 Copyright (c) 2014 Sebastian Schleemilch

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.itschleemilch.mixprocessing.welcome;

import de.itschleemilch.mixprocessing.LoggingDialog;
import de.itschleemilch.mixprocessing.ScriptingFrame;
import de.itschleemilch.mixprocessing.load.JarManagement;
import de.itschleemilch.mixprocessing.util.FolderShortcuts;
import de.itschleemilch.mixprocessing.util.InternetShortcuts;
import de.itschleemilch.mixprocessing.util.SinglePreference;
import de.itschleemilch.mixprocessing.webserver.Webserver;
import java.io.File;

/**
 *
 * @author Sebastian
 */
public class WelcomeFrame extends javax.swing.JFrame {
    private final LoggingDialog logDialog;
    private final ScriptingFrame scriptFrame;

    /**
     * Creates new form WelcomeFrame
     * 
     * @param logDialog
     * @param scriptFrame 
     */
    public WelcomeFrame(LoggingDialog logDialog, ScriptingFrame scriptFrame) {
        super();
        this.logDialog = logDialog;
        this.scriptFrame = scriptFrame;
        initComponents();
        pack();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        viewMenu = new javax.swing.JMenu();
        webInterfaceItem = new javax.swing.JMenuItem();
        fileLocMenu = new javax.swing.JMenu();
        prefsLoclItem = new javax.swing.JMenuItem();
        webserverLoclItem = new javax.swing.JMenuItem();
        sketchesLoclItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        scriptConsoleItem = new javax.swing.JMenuItem();
        debugItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        userManualItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        websiteItem = new javax.swing.JMenuItem();
        projectHomelItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        aboutlItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mission Control");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/itschleemilch/mixprocessing/res/MixProcessing-Logo_256x256.png"))); // NOI18N
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");
        jMenuBar1.add(fileMenu);

        viewMenu.setText("View");

        webInterfaceItem.setText("Web Interface");
        webInterfaceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webInterfaceItemActionPerformed(evt);
            }
        });
        viewMenu.add(webInterfaceItem);

        fileLocMenu.setText("File Locations");

        prefsLoclItem.setText("Preferences");
        prefsLoclItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefsLoclItemActionPerformed(evt);
            }
        });
        fileLocMenu.add(prefsLoclItem);

        webserverLoclItem.setText("Webserver");
        webserverLoclItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webserverLoclItemActionPerformed(evt);
            }
        });
        fileLocMenu.add(webserverLoclItem);

        sketchesLoclItem.setText("Exported Sketches");
        sketchesLoclItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sketchesLoclItemActionPerformed(evt);
            }
        });
        fileLocMenu.add(sketchesLoclItem);

        viewMenu.add(fileLocMenu);
        viewMenu.add(jSeparator3);

        scriptConsoleItem.setText("User Scripts");
        scriptConsoleItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scriptConsoleItemActionPerformed(evt);
            }
        });
        viewMenu.add(scriptConsoleItem);

        debugItem.setText("Log Messages");
        debugItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugItemActionPerformed(evt);
            }
        });
        viewMenu.add(debugItem);

        jMenuBar1.add(viewMenu);

        helpMenu.setText("Help");

        userManualItem.setText("User Manual");
        userManualItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManualItemActionPerformed(evt);
            }
        });
        helpMenu.add(userManualItem);
        helpMenu.add(jSeparator1);

        websiteItem.setText("MixProcessing Website");
        websiteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                websiteItemActionPerformed(evt);
            }
        });
        helpMenu.add(websiteItem);

        projectHomelItem.setText("Project Home");
        projectHomelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectHomelItemActionPerformed(evt);
            }
        });
        helpMenu.add(projectHomelItem);
        helpMenu.add(jSeparator2);

        aboutlItem.setText("About");
        aboutlItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutlItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutlItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void webInterfaceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webInterfaceItemActionPerformed
        InternetShortcuts.openShortcut(Webserver.getLocalServerURL());
    }//GEN-LAST:event_webInterfaceItemActionPerformed

    private void debugItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugItemActionPerformed
        logDialog.setVisible(true);
    }//GEN-LAST:event_debugItemActionPerformed

    private void scriptConsoleItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scriptConsoleItemActionPerformed
        scriptFrame.setVisible(true);
    }//GEN-LAST:event_scriptConsoleItemActionPerformed

    private void prefsLoclItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefsLoclItemActionPerformed
        FolderShortcuts.openShortcut(SinglePreference.getParentFolder());
    }//GEN-LAST:event_prefsLoclItemActionPerformed

    private void webserverLoclItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webserverLoclItemActionPerformed
        String webfilesDir = SinglePreference.getPreference(
                Webserver.KEY_STORAGE, "");
        FolderShortcuts.openShortcut( new File(webfilesDir) );
    }//GEN-LAST:event_webserverLoclItemActionPerformed

    private void sketchesLoclItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sketchesLoclItemActionPerformed
        String jarDir = SinglePreference.getPreference( 
                JarManagement.KEY_SKETCH_JAR_SOURCE, "" );
        FolderShortcuts.openShortcut( new File(jarDir) );
    }//GEN-LAST:event_sketchesLoclItemActionPerformed

    private void userManualItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManualItemActionPerformed
        InternetShortcuts.openShortcut(InternetShortcuts.USER_MANUAL);
    }//GEN-LAST:event_userManualItemActionPerformed

    private void websiteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_websiteItemActionPerformed
        InternetShortcuts.openShortcut(InternetShortcuts.PROJECT_WEBSITE);
    }//GEN-LAST:event_websiteItemActionPerformed

    private void projectHomelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectHomelItemActionPerformed
        InternetShortcuts.openShortcut(InternetShortcuts.PROJECT_HOME);
    }//GEN-LAST:event_projectHomelItemActionPerformed

    private void aboutlItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutlItemActionPerformed
        
    }//GEN-LAST:event_aboutlItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutlItem;
    private javax.swing.JMenuItem debugItem;
    private javax.swing.JMenu fileLocMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem prefsLoclItem;
    private javax.swing.JMenuItem projectHomelItem;
    private javax.swing.JMenuItem scriptConsoleItem;
    private javax.swing.JMenuItem sketchesLoclItem;
    private javax.swing.JMenuItem userManualItem;
    private javax.swing.JMenu viewMenu;
    private javax.swing.JMenuItem webInterfaceItem;
    private javax.swing.JMenuItem webserverLoclItem;
    private javax.swing.JMenuItem websiteItem;
    // End of variables declaration//GEN-END:variables

    private static final long serialVersionUID = 1L;
}
